name:                powermenu
version:             0.1.0.0
github:              "Kibadda/powermenu"
license:             MIT
author:              "Michael Strobel"
maintainer:          "mstrobel97@gmail.com"
copyright:           "2022 Michael Strobel"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/powermenu#readme>

dependencies:
- base >= 4.7 && < 5
- process
- brick
- vty
- optparse-applicative

library:
  source-dirs: src

executables:
  powermenu:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - powermenu

tests:
  powermenu-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - powermenu
